const express = require('express');
const router = express.Router();
const upload = require('../config/multer');
const {uploadProfileImage} = require('../controllers/authController');
const { register, login, getUser, updateUser, deleteUser } = require('../controllers/authController');
router.post('/register', register);
router.post('/login', login);
router.get('/users', getUser);
router.put('/users/:id', updateUser);
router.delete('/users/:id', deleteUser);
router.post("/upload/:id", upload.single("Image"), uploadProfileImage);
module.exports = router;